BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "balena-allwinner"
BBFILE_PATTERN_balena-allwinner := "^${LAYERDIR}/"
BBFILE_PRIORITY_balena-allwinner = "1337"

KERNEL_IMAGETYPES:balena-allwinner = "Image"
KERNEL_CLASSES:balena-allwinner = "kernel-uimage"

LAYERSERIES_COMPAT_balena-allwinner = "dunfell honister kirkstone scarthgap"
