#@TYPE: Machine
#@NAME: ty33a-8g1g
#@DESCRIPTION: Machine configuration for the TY33A 8G 1G A33 board (Allwinner A33)

require conf/machine/include/sun8i.inc

# Use our custom kernel configuration with proper MMC support
PREFERRED_VERSION_linux-mainline = "5.15.35"

KERNEL_DEVICETREE = "sun8i-a33-ty33a-8g1g.dtb"
# KERNEL_DEVICETREE = "sun8i-r16-bananapi-m2m.dtb"
UBOOT_MACHINE = "ty33a_8g1g_defconfig"

OS_DEVELOPMENT = "1"
UBOOT_EXTLINUX_DEBUG = "1"

# Enable UART debug for U-Boot (if not already in defconfig)
#UBOOT_CONFIG += " uart_debug"

# Serial console (adjust if needed)
SERIAL_CONSOLES = "115200;ttyS0"
SERIAL_CONSOLES_CHECK = "115200;ttyS0"

# Include Realtek RTL8723 firmware
MACHINE_EXTRA_RRECOMMENDS += " linux-firmware-rtl8723"

# Add the rtl8723cs wifi driver
MACHINE_EXTRA_RRECOMMENDS += "rtl8723cs"
KERNEL_MODULE_AUTOLOAD += "8723cs"

# Install the out-of-tree rtl8723cs module into the image
IMAGE_INSTALL += " rtl8723cs"